// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-g91RY4pjC3LQyAOPo9fLjibS83gSTuQ',
    appId: '1:124605377629:android:d437fcb73e2d3b9e99b1b4',
    messagingSenderId: '124605377629',
    projectId: 'linen-republic',
    storageBucket: 'linen-republic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVK8f1ATVvbxRhshwas4APL5cQg_t5DIc',
    appId: '1:124605377629:ios:a318a9fc22f8c38c99b1b4',
    messagingSenderId: '124605377629',
    projectId: 'linen-republic',
    storageBucket: 'linen-republic.appspot.com',
    androidClientId: '124605377629-obamhj4k248pfdikj0v82hoapfim9ork.apps.googleusercontent.com',
    iosClientId: '124605377629-58p2sasoh9j56nhe9r8t9jup851vpcb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.linenRepublicAdmin',
  );
}
